spring.datasource.url=jdbc:postgresql://localhost:9999/cashflowsystemdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=snehasis@2005

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.main.web-application-type=servlet
spring.main.lazy-initialization=true

spring.sql.init.mode=never